### ISSUE TITLE
can't find the file "lane_candidates_1000.pickle",but it exists

### ISSUE THREAD

**Issue by GongDianCheng** [dongkwonjin/Eigenlanes#4]
First I'd like to thank you for your great work and your open source. I download the code today and want to test the performance on tusimple, here is my command:
` python main.py --run_mode test_paper --pre_dir ROOT/preprocessed/tusimple/ --paper_weight_dir ROOT/pretrained/tusimple/ --dataset_dir ROOT/dataset/
`
however,it has some problems like this：
`Traceback (most recent call last):
  File "main.py", line 51, in <module>
    main()
  File "main.py", line 35, in main
    dict_DB = prepare_visualization(cfg, dict_DB)
  File "/home/gdc/gong/lane-detection/EigenlanesCVPR2022/ROOT/Modeling/tusimple/code/libs/prepare.py", line 41, in prepare_visualization
    dict_DB['visualize'] = Visualize_cv(cfg=cfg)
  File "/home/gdc/gong/lane-detection/EigenlanesCVPR2022/ROOT/Modeling/tusimple/code/visualizes/visualize.py", line 24, in __init__
    self.candidates = load_pickle(self.cfg.dir['pre3'] + 'lane_candidates_' + str(self.cfg.n_clusters))
  File "/home/gdc/gong/lane-detection/EigenlanesCVPR2022/ROOT/Modeling/tusimple/code/libs/utils.py", line 76, in load_pickle
    with open(file_path + '.pickle', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'ROOT/preprocessed/tusimple/P03_clustering/output_train_set/pickle/lane_candidates_1000.pickle'

`
I'm sure there is that file in that directory。And，If I want to test some pictures，what should I do?Put all the pictures in one folder  will work？
Any advice would be greatly appreciated

**Comment by tingxr** [comment]
> First I'd like to thank you for your great work and your open source. I download the code today and want to test the performance on tusimple, here is my command: `python main.py --run_mode test_paper --pre_dir ROOT/preprocessed/tusimple/ --paper_weight_dir ROOT/pretrained/tusimple/ --dataset_dir ROOT/dataset/` however,it has some problems like this： `Traceback (most recent call last): File "main.py", line 51, in main() File "main.py", line 35, in main dict_DB = prepare_visualization(cfg, dict_DB) File "/home/gdc/gong/lane-detection/EigenlanesCVPR2022/ROOT/Modeling/tusimple/code/libs/prepare.py", line 41, in prepare_visualization dict_DB['visualize'] = Visualize_cv(cfg=cfg) File "/home/gdc/gong/lane-detection/EigenlanesCVPR2022/ROOT/Modeling/tusimple/code/visualizes/visualize.py", line 24, in **init** self.candidates = load_pickle(self.cfg.dir['pre3'] + 'lane_candidates_' + str(self.cfg.n_clusters)) File "/home/gdc/gong/lane-detection/EigenlanesCVPR2022/ROOT/Modeling/tusimple/code/libs/utils.py", line 76, in load_pickle with open(file_path + '.pickle', 'rb') as f: FileNotFoundError: [Errno 2] No such file or directory: 'ROOT/preprocessed/tusimple/P03_clustering/output_train_set/pickle/lane_candidates_1000.pickle'
> 
> ` I'm sure there is that file in that directory。And，If I want to test some pictures，what should I do?Put all the pictures in one folder will work？ Any advice would be greatly appreciated

大佬，请问您看懂论文或者代码了没，有偿请教一下行不，我论文没看太懂

**Comment by GongDianCheng** [comment]
> 

原理看懂了，具体数学公式没看

**Comment by GongDianCheng** [comment]
@6098669 我只是看懂了文章的实现原理，具体的数学公式我跳过了

**Comment by tingxr** [comment]
> @6098669 我只是看懂了文章的实现原理，具体的数学公式我跳过了

老哥能否加个微信或qq，想请教您一下，这个数学公式我没看太懂

**Comment by ITBoy-China** [comment]
@GongDianCheng 

老哥，作者代码的测试部分，我已经成功跑起来了。关于你这个文件找不到的问题，我看你的`pre_dir`是这个`ROOT/preprocessed/tusimple/`，这样是会从linux的根目录去找的，除非你根目录里有这个文件或者文件夹，又或者权限不够。我在windows上跑的命令是这个，你可以参考一下：`python main.py --run_mode test_paper --pre_dir D:/browser/download/preprocessed/tusimple/ --dataset_dir F:/dataset/tusimple/`

有问题之后可以详细交流一下~  顺便问一下，看你的id，感觉好像是本科校友

**Comment by ITBoy-China** [comment]
> @GongDianCheng
> 
> 老哥，作者代码的测试部分，我已经成功跑起来了。关于你这个文件找不到的问题，我看你的`pre_dir`是这个`ROOT/preprocessed/tusimple/`，这样是会从linux的根目录去找的，除非你根目录里有这个文件或者文件夹，又或者权限不够。我在windows上跑的命令是这个，你可以参考一下：`python main.py --run_mode test_paper --pre_dir D:/browser/download/preprocessed/tusimple/ --dataset_dir F:/dataset/tusimple/`
> 
> 有问题之后可以详细交流一下~ 顺便问一下，看你的id，感觉好像是本科校友

作者训练好的权重我直接在作者代码的配置里修改了，所以在执行程序的时候，传参就没有加上去

**Comment by GongDianCheng** [comment]
> @GongDianCheng
> 
> 老哥，作者代码的测试部分，我已经成功跑起来了。关于你这个文件找不到的问题，我看你的`pre_dir`是这个`ROOT/preprocessed/tusimple/`，这样是会从linux的根目录去找的，除非你根目录里有这个文件或者文件夹，又或者权限不够。我在windows上跑的命令是这个，你可以参考一下：`python main.py --run_mode test_paper --pre_dir D:/browser/download/preprocessed/tusimple/ --dataset_dir F:/dataset/tusimple/`
> 
> 有问题之后可以详细交流一下~ 顺便问一下，看你的id，感觉好像是本科校友

这个你说得对，在linux下写绝对路径就成功了，忘记更新这里了，我当时以为那个ROOT是项目的根目录

**Comment by GongDianCheng** [comment]
> 

哈哈哈哈，真假，可以加一波好友，vx：g8002117255，以后可直接交流

**Comment by dongkwonjin** [comment]
Thank you for your attention!! we are sorry for the late reply. 
If you have any further questions, please feel free to contact us :)
