### ISSUE TITLE
ABOUT THE SPEED

### ISSUE THREAD

**Issue by ITBoy-China** [dongkwonjin/Eigenlanes#5]
Thanks for your great work. I'm puzzled at the speed cause I just ran 14 fps on my pc.Here are the configurations of my pc.

- CPU-------Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
- GPU-------NVIDIA GTX 1050 4GB
- Memory-- 24GB

Could you please show me the configurations of your machine where you ran 101 fps?

**Comment by dongkwonjin** [comment]
Thank you for your attention!

Below we list the configurations.

CPU-------AMD RYZEN 9 5900X @ 3.70GHz
GPU-------RTX 3090 24GB
Memory-- 64GB

**Comment by ITBoy-China** [comment]
> Thank you for your attention!
> 
> Below we list the configurations.
> 
> CPU-------AMD RYZEN 9 5900X @ 3.70GHz GPU-------RTX 3090 24GB Memory-- 64GB

Thanks for your patient reply. By the way , do you run your model on gpu to get the speed ? Or just using cpu to inference .

**Comment by dongkwonjin** [comment]
We run the model on gpu.

**Comment by ITBoy-China** [comment]
> We run the model on gpu.

Thank you very much! With best wishes!
